version: '3.3'
services:
  php:
    container_name: php-app
    ports:
      - 8081:80
    volumes:
      - ../php-jahitin:/var/www/html
    build:
      context: ../php-jahitin
      dockerfile: Dockerfile
    environment:
      - UPLOAD_LIMIT=10M

  soap:
    container_name: soap-app
    ports:
      - 8003:8003
    build:
      context: ../soap-jahitin/soap-service
      dockerfile: Dockerfile

  mysql_db:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - ./php-jahitin/src/databases/jahitin.sql:/docker-entrypoint-initdb.d/jahitin.sql
    environment:
      - MYSQL_DATABASE=jahitin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    
  phpmyadmin:
    container_name: phpmyadmin-gui
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306

  soap-jahitin-db:
    container_name: soap-jahitin-db
    image: mysql:latest
    ports:
      - "3003:3003"
    volumes:
      - ../soap-jahitin/soap-service/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soap_jahitin
      MYSQL_USER: user
      MYSQL_PASSWORD: jahitin
